# Generated by Django 5.0.6 on 2024-06-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_fees',
            field=models.PositiveBigIntegerField(),
        ),
    ]
