# Generated by Django 5.0.6 on 2024-07-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_starttime', models.TimeField()),
                ('class_endtime', models.TimeField()),
                ('class_course', models.CharField(max_length=50)),
                ('class_classroom', models.CharField(max_length=20)),
                ('class_dayofweek', models.CharField(max_length=20)),
            ],
        ),
    ]
